runtime: nodejs20

handlers:
  - url: /assets/(.*\..+)$
    static_files: dist/assets/\1
    upload: dist/assets/(.*\..+)$
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html